table ref_references
	lineageTag: b885eee8-b7ee-4f2f-9ec6-ed55be4ca767

	measure 'Avg Requested To Reviewed Time (Days)' = AVERAGE(ref_references[requested_to_reviewed_time]) / 86400
		lineageTag: 041a0674-71e9-4b34-9cad-d74563756b46

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Requested To Submitted Time' = AVERAGE(ref_references[requested_to_completed_time]) / 3600
		lineageTag: 66928b21-7fd6-46c2-9aad-085899a5ff6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Submitted To Reviewed Time' = AVERAGE(ref_references[completed_to_reviewed_time])
		lineageTag: 385f93cf-9173-4941-862c-8656e5462482

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Number of Approved References' = COUNT(ref_references[ref_approved_at])
		formatString: 0
		lineageTag: 1669d29c-abae-4076-8450-325285ca51c5

	measure 'Number of Submitted References' = COUNT(ref_references[requested_to_completed_time])
		formatString: # ##0
		lineageTag: 571e7b98-73cc-4750-8f12-2cb3d219067f

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Number of Months for Rolling Avg' = 3
		formatString: 0
		lineageTag: 7265594d-34ca-4b81-8e8e-a893d41f95d1

	measure 'Number of References' = COUNTROWS(ref_references) + 0
		formatString: # ##0
		lineageTag: fe038b7a-df2e-4144-9133-1f64b61e0628

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Rolling Avg Submitted to Reviewed Days' = ```
			
			CALCULATE (
			    AVERAGEX (ref_references, ref_references[completed_to_reviewed_time]),
			    DATESINPERIOD (
			        Dates[Date],
			        LASTDATE (Dates[Date]),
			        -[Number of Months for Rolling Avg],
			        MONTH
			    ),
			    USERELATIONSHIP(
			        ref_references[ref_approved_date], 
			        Dates[Date]
			    )
			) / (60*60*24)
			```
		lineageTag: 7bc574af-90e6-4521-8da0-d2d37e48ebbe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rolling Avg Requested to Submitted Days' =
			
			CALCULATE (
			    AVERAGEX (ref_references, ref_references[requested_to_completed_time]),
			    DATESINPERIOD (
			        Dates[Date],
			        LASTDATE (Dates[Date]),
			        -[Number of Months for Rolling Avg],
			        MONTH
			    )
			) / (60*60*24)
		lineageTag: 7782a940-1041-4e40-aec4-6602b6abdc92

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rolling Avg Requested to Reviewed Days' =
			
			CALCULATE (
			    AVERAGEX (ref_references, ref_references[requested_to_reviewed_time]),
			    DATESINPERIOD (
			        Dates[Date],
			        LASTDATE (Dates[Date]),
			        -[Number of Months for Rolling Avg],
			        MONTH
			    )
			) / (60*60*24)
		lineageTag: 05c43ece-3a31-45a5-b65d-28685ca8eab2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Reviewed Within SLA (5 Days)' =
			
			VAR SLA_SECONDS = 432000
			VAR SelectedEndDate = MAX('Dates'[Date])
			
			RETURN
			DIVIDE(
			    COUNTROWS(
			        FILTER(
			            ref_references,
			            (
			                -- SLA Pass: Approved/Denied and reviewed in ≤ 5 days
			                ref_references[ref_status] IN {"Approved", "Denied"} &&
			                ref_references[requested_to_reviewed_time] <= SLA_SECONDS
			            )
			        )
			    ),
			    COUNTROWS(
			        FILTER(
			            ref_references,
			            (
			                -- Approved/Denied (always included)
			                ref_references[ref_status] IN {"Approved", "Denied"}
			            )
			            ||
			            (
			                -- Awaiting Approval and request is older than 5 days (based on selected end date)
			                ref_references[ref_status] = "Awaiting_Approval" &&
			                DATEDIFF(ref_references[ref_requested_at], SelectedEndDate, SECOND) > SLA_SECONDS
			            )
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 07ba385c-81a0-48fc-afdb-992aef53502d

	measure '# Reviews Awaiting Approval' =
			
			CALCULATE(
			    COUNTROWS(ref_references),
			    ref_references[ref_status] = "Awaiting_Approval"
			)
		formatString: 0
		lineageTag: 8614fafc-1368-4436-bfd6-58bedd685fe6

	measure '% Mandatory Approved On Time' = ```
			
			VAR SLA_SECONDS = 432000
			VAR SelectedEndDate = MAX('Dates'[Date])
			
			RETURN
			DIVIDE(
			    -- Count of mandatory references approved or denied within SLA
			    COUNTROWS(
			        FILTER(
			            ref_references,
			            ref_references[is_mandatory] = TRUE() &&
			            ref_references[ref_status] IN {"Approved", "Denied"} &&
			            ref_references[requested_to_reviewed_time] <= SLA_SECONDS
			        )
			    ),
			    --  Total mandatory references that should have been reviewed
			    COUNTROWS(
			        FILTER(
			            ref_references,
			            ref_references[is_mandatory] = TRUE() &&
			            (
			                ref_references[ref_status] IN {"Approved", "Denied"} ||
			                (
			                    ref_references[ref_status] = "Awaiting_Approval" &&
			                    DATEDIFF(ref_references[ref_requested_at], SelectedEndDate, SECOND) > SLA_SECONDS
			                )
			            )
			        )
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c4bb7570-c498-4843-952e-b5fc6a8cda6d

	measure '% Non-Mandatory Approved On Time' = ```
			
			VAR SLA_SECONDS = 432000
			VAR SelectedEndDate = MAX('Dates'[Date])
			
			RETURN
			DIVIDE(
			    -- Count of mandatory references approved or denied within SLA
			    COUNTROWS(
			        FILTER(
			            ref_references,
			            ref_references[is_mandatory] = FALSE() &&
			            ref_references[ref_status] IN {"Approved", "Denied"} &&
			            ref_references[requested_to_reviewed_time] <= SLA_SECONDS
			        )
			    ),
			   -- Total mandatory references that should have been reviewed
			    COUNTROWS(
			        FILTER(
			            ref_references,
			            ref_references[is_mandatory] = FALSE() &&
			            (
			                ref_references[ref_status] IN {"Approved", "Denied"} ||
			                (
			                    ref_references[ref_status] = "Awaiting_Approval" &&
			                    DATEDIFF(ref_references[ref_requested_at], SelectedEndDate, SECOND) > SLA_SECONDS
			                )
			            )
			        )
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3d1ba0e9-00bf-4d84-aaa9-2149a8e59797

	measure '# Mandatory Reviews Awaiting Approval' =
			
			CALCULATE(
			    COUNTROWS(ref_references),
			    ref_references[ref_status] = "Awaiting_Approval",
			    ref_references[is_mandatory] = TRUE()
			)
		formatString: 0
		lineageTag: 35199814-21c0-4ea7-a373-182be4b6b8c2

	measure 'Target Mandatory Completed Within SLA' = 0.6
		formatString: 0%;-0%;0%
		lineageTag: e6f338c9-5563-41f1-97f6-f9fd2f5acc5e

	measure 'Target Total Completed Within SLA' = 0.5
		formatString: 0%;-0%;0%
		lineageTag: 78a86bdf-7a71-4960-9dba-7e5909b895e6

	column completed_to_reviewed_days
		dataType: int64
		lineageTag: 23629e9c-98e8-470a-b6a3-04d973f3462c
		summarizeBy: none
		sourceColumn: completed_to_reviewed_days

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation SummarizationSetBy = User

	column completed_to_reviewed_time
		dataType: double
		lineageTag: 0e6cfed2-2615-438d-af84-6853ec889c5f
		summarizeBy: sum
		sourceColumn: completed_to_reviewed_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cr_created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: fd8ae5a7-4295-4dd8-9852-84ddfb7abde8
		summarizeBy: none
		sourceColumn: cr_created_at

		annotation SummarizationSetBy = Automatic

	column job_position_id
		dataType: int64
		formatString: 0
		lineageTag: 499c4c8c-744c-4b9e-91a0-f720075f052c
		summarizeBy: none
		sourceColumn: job_position_id

		annotation SummarizationSetBy = Automatic

	column marked_compliant_at
		dataType: dateTime
		formatString: General Date
		lineageTag: a3f7d584-2d3c-4e2a-916e-34adf2da4340
		summarizeBy: none
		sourceColumn: marked_compliant_at

		annotation SummarizationSetBy = Automatic

	column ref_approval_status
		dataType: string
		lineageTag: 8d140338-c260-4689-9f92-89a606f666b5
		summarizeBy: none
		sourceColumn: ref_approval_status

		annotation SummarizationSetBy = Automatic

	column ref_approved_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 7ff57eb8-6ca7-45bc-8b04-619c291f01da
		summarizeBy: none
		sourceColumn: ref_approved_at

		annotation SummarizationSetBy = Automatic

	column ref_approved_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 76e1ce4e-a2eb-41ef-9759-f80f2c52078d
		summarizeBy: none
		sourceColumn: ref_approved_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ref_completed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: d8c991f5-3ad3-49b5-bc02-afffa731d9c2
		summarizeBy: none
		sourceColumn: ref_completed_at

		annotation SummarizationSetBy = Automatic

	column ref_completed_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3416eb6a-af72-4a4e-bbca-e8c90d25fd42
		summarizeBy: none
		sourceColumn: ref_completed_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ref_requested_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 5a78b2db-c16f-4097-9d11-45e497daa335
		summarizeBy: none
		sourceColumn: ref_requested_at

		annotation SummarizationSetBy = Automatic

	column ref_requested_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f94f6bd6-c89f-4c1e-ab96-c1ca3e7bc6e8
		summarizeBy: none
		sourceColumn: ref_requested_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ref_status
		dataType: string
		lineageTag: b6f45942-620d-438f-be38-a38cb51882ce
		summarizeBy: none
		sourceColumn: ref_status

		annotation SummarizationSetBy = Automatic

	column requested_to_completed_days
		dataType: int64
		lineageTag: 17416bd8-6afd-44af-b464-b18d86d98f13
		summarizeBy: none
		sourceColumn: requested_to_completed_days

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation SummarizationSetBy = User

	column requested_to_completed_time
		dataType: double
		lineageTag: 483615f0-6590-491f-ac76-7bdf4057728f
		summarizeBy: sum
		sourceColumn: requested_to_completed_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column requested_to_compliant_time
		dataType: double
		lineageTag: bcc01aa2-fa25-47b3-b88e-c408aef4b799
		summarizeBy: sum
		sourceColumn: requested_to_compliant_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column requested_to_reviewed_time
		dataType: double
		lineageTag: 3b27de7d-a880-4f41-bc8b-ad7f7f23dd2c
		summarizeBy: sum
		sourceColumn: requested_to_reviewed_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_mandatory
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2a337263-ea0e-42e8-ac94-380320303a74
		summarizeBy: none
		sourceColumn: is_mandatory

		annotation SummarizationSetBy = Automatic

	column ref_package_name
		dataType: string
		lineageTag: f2df5504-f1f0-4fe6-a5fe-b5767d3b808a
		summarizeBy: none
		sourceColumn: ref_package_name

		annotation SummarizationSetBy = Automatic

	column ref_form_name
		dataType: string
		lineageTag: 650694b2-e78a-4195-8b90-28f49af2635b
		summarizeBy: none
		sourceColumn: ref_form_name

		annotation SummarizationSetBy = Automatic

	column requested_to_reviewed_days
		dataType: string
		lineageTag: b8613b63-7049-4b73-9dc2-d240c93c18d3
		summarizeBy: none
		sourceColumn: requested_to_reviewed_days

		annotation SummarizationSetBy = Automatic

	column requested_to_compliant_days
		dataType: string
		lineageTag: 216a1058-ec07-4b09-8bc3-93d72b361118
		summarizeBy: none
		sourceColumn: requested_to_compliant_days

		annotation SummarizationSetBy = Automatic

	column requested_to_completed_category
		dataType: string
		lineageTag: 3445cad6-7d3b-468a-960b-86e27b44a13b
		summarizeBy: none
		sourceColumn: requested_to_completed_category

		annotation SummarizationSetBy = Automatic

	column completed_to_reviewed_category
		dataType: string
		lineageTag: 442ced99-a31c-4a04-8d71-1da100958f7f
		summarizeBy: none
		sourceColumn: completed_to_reviewed_category

		annotation SummarizationSetBy = Automatic

	column requested_to_reviewed_category
		dataType: string
		lineageTag: 126b24a3-d8c4-47cb-9a3b-9cd610b3da3a
		summarizeBy: none
		sourceColumn: requested_to_reviewed_category

		annotation SummarizationSetBy = Automatic

	column requested_to_compliant_category
		dataType: string
		lineageTag: 3ce52e0d-ceea-47b4-bfb4-bbb143ada6fe
		summarizeBy: none
		sourceColumn: requested_to_compliant_category

		annotation SummarizationSetBy = Automatic

	column is_valid =
			
			SWITCH(
			    TRUE(),
			    ref_references[ref_status] = "AWAITING_APPROVAL" && ISBLANK(ref_references[ref_completed_at]), "N",
			    ref_references[ref_status] = "APPROVED" && (ISBLANK(ref_references[ref_completed_at]) || ISBLANK(ref_references[ref_approved_at])), "N",
			    ref_references[ref_status] = "DENIED" && (ISBLANK(ref_references[ref_completed_at]) || ISBLANK(ref_references[ref_approved_at])), "N",
			    "Y"
			)
		lineageTag: bbc4628c-7d84-4429-aad0-f9776109d496
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition ref_references = m
		mode: import
		queryGroup: References
		source =
				let
								    Source = Csv.Document(Web.Contents("https://drive.google.com/uc?export=download&id=1mQj30vUWHMDdVPJVJk4qLh9jD3BYCvSM"),
				        								  [Delimiter = ",", Encoding = 65001]),
				    				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
								    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"job_position_id", Int64.Type}, {"ref_requested_at", type datetime}, {"ref_requested_date", type date}, {"ref_completed_at", type datetime}, {"ref_completed_date", type date}, {"ref_approved_at", type datetime}, {"ref_approved_date", type date}, {"is_mandatory", type logical}, {"ref_package_name", type text}, {"ref_form_name", type text}, {"cr_created_at", type datetime}, {"marked_compliant_at", type datetime}, {"requested_to_completed_time", type number}, {"completed_to_reviewed_time", type number}, {"requested_to_reviewed_time", type number}, {"requested_to_compliant_time", type number}, {"ref_status", type text}, {"ref_approval_status", type text}, {"requested_to_completed_days", Int64.Type}, {"completed_to_reviewed_days", Int64.Type}})
								in
								    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

